@baseUrl = "http://localhost:3333"
@authToken = {{{{{authenticate.response.body.access_token}}}}}


# @name create_account
POST {{baseUrl}}/accounts HTTP/1.1
Content-Type:: application/json

{
  "name": "Julio Tavares",
  "email": "julio@test.me",
  "password": "123456"
}

###

# @name authenticate

POST  {{baseUrl}}/sessions HTTP/1.1
Content-Type: application/json

{
  "email": "julio@test.me",
  "password": "123456"
}

# @name create_question

POST {{baseUrl}}/questions HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}